### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by genericmilk** [AnSavvides/jquery.linky#7]
Hi there,

Just so you guys are aware, On your documentation you've listed the function name as $('className').linkify({options});

This needs to be corrected to $('className').linky({options});

Thanks!

**Comment by AnSavvides** [comment]
Well spotted @genericmilk, thank you! :)

Would you like to fork this repo and make the change yourself? I could do it, but since you spotted it you deserve to get the contribution if anything :)
